
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Sun May 08 14:58:48 CEST 2022
//----------------------------------------------------

package tiny1.ast_ascendente;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int DISTINTO = 22;
  public static final int POR = 12;
  public static final int SEP_SEC = 5;
  public static final int PCIERRE = 24;
  public static final int INT = 2;
  public static final int ARRAY = 46;
  public static final int CORAPERTURA = 26;
  public static final int WRITE = 52;
  public static final int DELETE = 50;
  public static final int NOT = 16;
  public static final int AND = 14;
  public static final int RECORD = 45;
  public static final int TYPE = 55;
  public static final int OR = 15;
  public static final int BOOL = 4;
  public static final int CALL = 44;
  public static final int DIV = 13;
  public static final int IF = 37;
  public static final int AMPERSAND = 32;
  public static final int ENDWHILE = 43;
  public static final int OF = 47;
  public static final int EOF = 0;
  public static final int TRUE = 8;
  public static final int NEW = 49;
  public static final int error = 1;
  public static final int COMA = 33;
  public static final int CADENA = 59;
  public static final int POR_CIENTO = 25;
  public static final int MENOS = 11;
  public static final int NULL = 35;
  public static final int MENOR = 17;
  public static final int MAYOR_IG = 20;
  public static final int PCOMA = 6;
  public static final int REAL = 3;
  public static final int MAYOR = 18;
  public static final int FLECHA = 31;
  public static final int ENDIF = 40;
  public static final int NUM_REAL = 57;
  public static final int ELSE = 39;
  public static final int PUNTO = 30;
  public static final int VARIABLE = 58;
  public static final int PAPERTURA = 23;
  public static final int NL = 53;
  public static final int READ = 51;
  public static final int LLAVE_APERTURA = 28;
  public static final int WHILE = 41;
  public static final int THEN = 38;
  public static final int IGUAL_COMP = 21;
  public static final int LLAVE_CIERRE = 29;
  public static final int NUM_ENTERO = 56;
  public static final int PROC = 36;
  public static final int STRING = 34;
  public static final int CORCIERRE = 27;
  public static final int POINTER = 48;
  public static final int FALSE = 9;
  public static final int MENOR_IG = 19;
  public static final int IGUAL_ASIG = 7;
  public static final int VAR = 54;
  public static final int DO = 42;
  public static final int MAS = 10;
}

