
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Wed Mar 23 20:22:21 CET 2022
//----------------------------------------------------

package tiny1.ast_ascendente;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int DISTINTO = 25;
  public static final int POR = 15;
  public static final int SEP_SEC = 5;
  public static final int PCIERRE = 27;
  public static final int INT = 2;
  public static final int ARRAY = 50;
  public static final int CORAPERTURA = 30;
  public static final int WRITE = 56;
  public static final int DELETE = 54;
  public static final int NOT = 19;
  public static final int AND = 17;
  public static final int RECORD = 49;
  public static final int TYPE = 59;
  public static final int OR = 18;
  public static final int BOOL = 4;
  public static final int CALL = 48;
  public static final int DIV = 16;
  public static final int IF = 41;
  public static final int AMPERSAND = 36;
  public static final int ENDWHILE = 47;
  public static final int OF = 51;
  public static final int EOF = 0;
  public static final int TRUE = 9;
  public static final int NEW = 53;
  public static final int error = 1;
  public static final int COMA = 37;
  public static final int POR_CIENTO = 29;
  public static final int CADENA = 28;
  public static final int MENOS = 14;
  public static final int NULL = 39;
  public static final int MENOR = 20;
  public static final int MAYOR_IG = 23;
  public static final int PCOMA = 6;
  public static final int REAL = 3;
  public static final int MAYOR = 21;
  public static final int FLECHA = 35;
  public static final int ENDIF = 44;
  public static final int ELSE = 43;
  public static final int NUM_REAL = 12;
  public static final int PUNTO = 34;
  public static final int VARIABLE = 7;
  public static final int PAPERTURA = 26;
  public static final int NL = 57;
  public static final int READ = 55;
  public static final int LLAVE_APERTURA = 32;
  public static final int WHILE = 45;
  public static final int THEN = 42;
  public static final int IGUAL_COMP = 24;
  public static final int LLAVE_CIERRE = 33;
  public static final int NUM_ENTERO = 11;
  public static final int PROC = 40;
  public static final int STRING = 38;
  public static final int CORCIERRE = 31;
  public static final int POINTER = 52;
  public static final int FALSE = 10;
  public static final int MENOR_IG = 22;
  public static final int IGUAL_ASIG = 8;
  public static final int VAR = 58;
  public static final int DO = 46;
  public static final int MAS = 13;
}

