/* Generated By:JavaCC: Do not edit this line. ConstructorASTConstants.java */
package tiny1.ast_descendente;

public interface ConstructorASTConstants {

  int EOF = 0;
  int letra = 1;
  int digitoPositivo = 2;
  int digito = 3;
  int parteEntera = 4;
  int parteDecimal = 5;
  int parteExponencial = 6;
  int signo = 7;
  int donde = 10;
  int evalua = 11;
  int numeroEntero = 12;
  int numeroReal = 13;
  int Int = 14;
  int bool = 15;
  int real = 16;
  int True = 17;
  int False = 18;
  int or = 19;
  int and = 20;
  int not = 21;
  int string = 22;
  int Null = 23;
  int proc = 24;
  int If = 25;
  int then = 26;
  int Else = 27;
  int endif = 28;
  int While = 29;
  int Do = 30;
  int endwhile = 31;
  int call = 32;
  int record = 33;
  int array = 34;
  int of = 35;
  int pointer = 36;
  int New = 37;
  int delete = 38;
  int read = 39;
  int write = 40;
  int nl = 41;
  int var = 42;
  int type = 43;
  int identificador = 44;
  int cadena = 45;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "<letra>",
    "<digitoPositivo>",
    "<digito>",
    "<parteEntera>",
    "<parteDecimal>",
    "<parteExponencial>",
    "<signo>",
    "<token of kind 8>",
    "<token of kind 9>",
    "\"donde\"",
    "\"evalua\"",
    "<numeroEntero>",
    "<numeroReal>",
    "\"int\"",
    "\"bool\"",
    "\"real\"",
    "\"true\"",
    "\"false\"",
    "\"or\"",
    "\"and\"",
    "\"not\"",
    "\"string\"",
    "\"null\"",
    "\"proc\"",
    "\"if\"",
    "\"then\"",
    "\"else\"",
    "\"endif\"",
    "\"while\"",
    "\"do\"",
    "\"endwhile\"",
    "\"call\"",
    "\"record\"",
    "\"array\"",
    "\"of\"",
    "\"pointer\"",
    "\"new\"",
    "\"delete\"",
    "\"read\"",
    "\"write\"",
    "\"nl\"",
    "\"var\"",
    "\"type\"",
    "<identificador>",
    "<cadena>",
    "\"&&\"",
    "\";\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\"&\"",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "\"=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\">\"",
    "\"<\"",
    "\">=\"",
    "\"<=\"",
    "\"==\"",
    "\"!=\"",
    "\"/\"",
    "\"%\"",
    "\".\"",
    "\"->\"",
  };

}
