package tiny1;

public enum ClaseLexica {
	INT, REAL, BOOL, SEP_SEC, PCOMA, VARIABLE, IGUAL_ASIG, TRUE, FALSE, NUM_ENTERO, NUM_REAL, MAS, MENOS, 
	POR, DIV, AND, OR, NOT, MENOR, MAYOR, MENOR_IG, MAYOR_IG, IGUAL_COMP, DISTINTO, PAPERTURA, PCIERRE, EOF, 
	CADENA, POR_CIENTO, CORAPERTURA, CORCIERRE, LLAVE_APERTURA, LLAVE_CIERRE, PUNTO, FLECHA, AMPERSAND, COMA, 
	STRING, NULL, PROC, IF, THEN, ELSE, ENDIF, WHILE, DO, ENDWHILE, CALL, RECORD, ARRAY, OF, POINTER, NEW, DELETE, 
	READ, WRITE, NL, VAR, TYPE
}
