package tiny0;

public enum ClaseLexica {
	INT, REAL, BOOL, SEP_SEC, PCOMA, VARIABLE, IGUAL_ASIG, TRUE, FALSE, NUM_ENTERO, NUM_REAL, MAS, MENOS, POR, DIV, AND,
	OR, NOT, MENOR, MAYOR, MENOR_IG, MAYOR_IG, IGUAL_COMP, DISTINTO, PAPERTURA, PCIERRE, EOF

}
